spring.application.name=sistema-gestao-vagas
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vagas_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:vagas_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:vagas_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
server.port=8080